version: "2.3"
services:
  opendatacam:
    restart: always
    runtime: nvidia
    image: opendatacam/opendatacam:v3.0.2-desktop
    build:
      context: ./
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - './config.json:/var/local/opendatacam/config.json'
      - './yolo-ants.weights:/var/local/darknet/yolo-ants.weights'
      - './yolo-ants.data:/var/local/darknet/cfg/yolo-ants.data'
      - './yolo-ants.cfg:/var/local/darknet/cfg/yolo-ants.cfg'
      - './yolo-ants.names:/var/local/darknet/cfg/yolo-ants.names'
    ports:
      - "8080:8080"
      - "8070:8070"
      - "8090:8090"
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container: